project:
  type: website

website:
  title: "Toolbox AI Waterkeringen"
  navbar:
    left:
      - reference/index.qmd
    # right:
      # - icon: github
        # href: https://github.com/REPOLINK
        # aria-label: GitHub

format:
  html:
    theme: solar
    css: styles.css
    toc: true

quartodoc:
  style: pkgdown
  dir: reference
  title: API Reference
  package: null
  sections:
    - title: Test section
      package: testscripts
      desc: Toolbox AI Waterkeringen
