project:
  type: website

website:
  title: "AI Toolbox Waterkeringen"
  search: false
  navbar:
    title: false
    left:
      - icon: house-fill
        href: "./index.html"
        aria-label: Home
    right:
      - more.qmd
      - about.qmd
      - contact.qmd

format:
  html:
    theme: solar
    css: assets/styles.css
    toc: true
